---
- name: Kubernetes

  hosts: master
  remote_user: root

  vars_files:
  - config.yml

  roles:
  - etcd
  - role: flanneld
    mode: master
  - docker
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: root

  vars_files:
  - config.yml

  roles:
  - role: flanneld
    mode: node
  - docker
  - role: kubernetes
    mode: node
