- name: Install etcd binaries
  copy: src=bin/{{ item }} dest=/usr/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - etcd
    - etcdctl

- name: Create etcd data dir directory
  file: path=/var/lib/etcd state=directory recurse=false

- name: Install etcd service definition
  template: src=etcd.service dest=/etc/systemd/system/etcd.service owner=root group=root mode=0644
  register: result

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Restart etcd
  service: name=etcd enabled=yes state=restarted
