- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - curl

- name: Create Kubernetes cert directory
  file: path=/etc/kubernetes/certs/ state=directory recurse=no owner=root group=root mode=0755

- name: Copy cert creation script
  copy: src="make_ca_cert.sh" dest=/etc/kubernetes/certs/make_ca_cert.sh mode=0755 owner=root group=root

- name: Check certs
  stat: path=/etc/kubernetes/certs/ca.crt
  register: ca

- block:
  - name: Create certs
    command: /etc/kubernetes/certs/make_ca_cert.sh {{ master.ip }} IP:{{ master.ip }},IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local

  when: not ca.stat.exists
