
- name: Install Kubernetes
  copy: src=bin/{{ ansible_architecture }}/{{ item }} dest=/usr/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - kubelet
    - kubectl

- name: Create Kubernetes config directory
  file: path=/etc/kubernetes/manifests/ state=directory recurse=no owner=root group=root mode=0755

- name: Add certs
  include: certs.yml
  when: mode == "master"

- name: Copy configuration
  template: src=kubernetes-{{ mode }}.yml dest=/etc/kubernetes/manifests/kubernetes.yaml

- name: Setup profile
  template: src=kubernetes_profile.sh dest=/etc/profile.d/kubernetes.sh mode=0644

- name: Install kubelet service definition
  template: src=kubelet.service dest=/etc/systemd/system/kubelet.service owner=root group=root mode=0644
  register: result

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Restart kubelet
  service: name=kubelet enabled=yes state=restarted
