---
- name: Add and update packages
  include: apt.yml

- name: Copy config
  template: src=hostapd.conf dest=/etc/hostapd/hostapd.conf

- name: Set config file
  lineinfile: dest=/etc/default/hostapd regexp="DAEMON_CONF=" line="DAEMON_CONF=/etc/hostapd/hostapd.conf"

- name: Enable dnsmasq
  service: enabled=yes state=started name=hostapd

- name: Switch off power management for WiFi
  lineinfile: dest=/etc/network/interfaces state=present line="wireless-power off" insertafter="^iface wlan0"
