apiVersion: v1
kind: Pod
metadata:
  name: kube-node
spec:
  hostNetwork: true
  containers:
    - name: "kube-proxy"
      image: "{{ images.hyperkube }}"
      args:
        - "/hyperkube"
        - "proxy"
        - "--master=http://master:8080"
        - "--v={{ debug_level }}"
      securityContext:
        privileged: true
