- name: Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes

- name: Add Hypriot Repo Key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add Hypriot Repo
  apt_repository: repo='deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ jessie main' state=present

- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: safe

- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - docker-hypriot
    - bridge-utils
