- name: Add and update packages
  include: apt.yml

- name: Ensure that target directory /etc/docker exists
  file: path=/etc/docker state=directory recurse=false

- name: Add docker_init.sh for waiting on flannel to startup
  template: src=docker_init.sh dest=/etc/docker/docker_init.sh mode=0755

- name: Install own docker service
  template: src=docker.service dest=/etc/systemd/system/docker.service owner=root group=root mode=0644
  register: result

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Restart docker
  service: name=docker enabled=yes state=restarted
